#!/usr/bin/env python3
"""Generates a random, deterministically-seeded, straight-line NuASM
program for differential testing (scripts/diff_test.sh) against Nemu.

Deliberately straight-line (no JMP/JZ/JNZ/CALL/RET): this generator's job
is breadth over ALU/memory/stack/MAC/matrix operand combinations, not
control flow -- the 13 hand-written programs in Nemu's programs/tests/
already exercise branches and calls structurally, see CHATGPT.md backlog
item 4. Two things are deliberately avoided, both because they are
Nemu's documented, deliberate divergence from real hardware (CHATGPT.md),
not bugs to rediscover every run:

  - DIV/MOD by a register known to hold zero: Nemu's Rust reference
    panics (crashes the whole process) instead of returning 0, so this
    would make the *test generator* unreliable, not find a real RTL bug.
    Every DIV/MOD divisor register is guaranteed non-zero by construction
    (see `nonzero_regs`).

  - Using an MMUL *result* matrix register as a later MMUL *source*:
    Nemu panics if a matrix cell doesn't fit in INT8 (see src/matrix.rs),
    which an MMUL result can violate but an MSET-populated cell never can
    (MSET's immediate is a single assembled byte, already INT8-range on
    both sides). Only MSET-populated matrix registers are ever used as
    MMUL sources here.

Usage:
    scripts/gen_random_program.py --seed 12345 --out /tmp/prog.nuasm [--count 60]
"""
import argparse
import random


REGS = list(range(1, 16))  # R1-R15 (R0 left alone, matching the project's
                            # existing hand-written test programs' style)
MATRIX_REGS = [0, 1, 2, 3]  # M0-M3

# Small, fixed, word-aligned scratch region for LOAD/STORE: clear of the
# program's own code (starts at address 0; a 60-instruction program with
# MSET-heavy matrix seeding can exceed 600 bytes, so this must sit well
# above that) and of the stack (grows down from MEM_SIZE=1024; this
# generator caps stack depth at 8 words, so it never goes below 992).
MEM_ADDRS = list(range(900, 992, 4))


def emit(lines, text):
    lines.append(text)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--count", type=int, default=60, help="approximate instruction count")
    args = ap.parse_args()

    rng = random.Random(args.seed)
    lines = [f"// auto-generated by gen_random_program.py --seed {args.seed}"]

    known_values = {}    # reg -> last constant value MOVI'd into it (best-effort)
    nonzero_regs = set()  # regs known-nonzero right now (invalidated on any later write)
    mset_matrix_regs = set()  # matrix regs populated only via MSET so far
    mmul_result_regs = set()  # matrix regs that hold an MMUL result

    stack_depth = 0
    max_stack_depth = 8

    def movi(reg, value):
        # nuasm's MOVI immediate parser (parse_u32 in src/assembler.rs)
        # only accepts unsigned decimal or 0x-hex -- no leading '-' -- so
        # any value outside 0..2^31-1 (including everything this
        # generator treats as "negative" via Python ints) must be emitted
        # as its unsigned 32-bit hex bit pattern instead of a decimal
        # literal.
        emit(lines, f"MOVI R{reg}, 0x{value & 0xFFFFFFFF:08X}")
        known_values[reg] = value
        if value != 0:
            nonzero_regs.add(reg)
        else:
            nonzero_regs.discard(reg)

    def touch(reg):
        nonzero_regs.discard(reg)
        known_values.pop(reg, None)

    def rand_reg():
        return rng.choice(REGS)

    def rand_i32():
        return rng.randint(-(2**31), 2**31 - 1)

    def rand_small_nonneg():
        return rng.randint(0, 255)

    def ensure_nonzero(reg):
        if reg not in nonzero_regs:
            v = rng.choice([1, -1, 7, -7, 42, 1000])
            movi(reg, v)

    ops = [
        "movi", "mov", "add", "sub", "mul", "div", "mod",
        "and", "or", "xor", "not", "shl", "shr",
        "cmp", "load", "store", "push", "pop",
        "mac", "macclr", "macread", "mset", "mmul", "relu", "out",
    ]

    for _ in range(args.count):
        op = rng.choice(ops)

        if op == "movi":
            movi(rand_reg(), rand_i32())

        elif op == "mov":
            d, s = rand_reg(), rand_reg()
            emit(lines, f"MOV R{d}, R{s}")
            if s in known_values:
                known_values[d] = known_values[s]
            else:
                touch(d)
            if s in nonzero_regs:
                nonzero_regs.add(d)
            else:
                nonzero_regs.discard(d)

        elif op in ("add", "sub", "mul", "and", "or", "xor", "shl", "shr"):
            d, a, b = rand_reg(), rand_reg(), rand_reg()
            emit(lines, f"{op.upper()} R{d}, R{a}, R{b}")
            touch(d)

        elif op in ("div", "mod"):
            d, a, b = rand_reg(), rand_reg(), rand_reg()
            ensure_nonzero(b)
            emit(lines, f"{op.upper()} R{d}, R{a}, R{b}")
            touch(d)

        elif op == "not":
            d, a = rand_reg(), rand_reg()
            emit(lines, f"NOT R{d}, R{a}")
            touch(d)

        elif op == "cmp":
            a, b = rand_reg(), rand_reg()
            emit(lines, f"CMP R{a}, R{b}")

        elif op == "load":
            d = rand_reg()
            addr_reg = rand_reg()
            movi(addr_reg, rng.choice(MEM_ADDRS))
            emit(lines, f"LOAD R{d}, R{addr_reg}")
            touch(d)

        elif op == "store":
            addr_reg, data_reg = rand_reg(), rand_reg()
            movi(addr_reg, rng.choice(MEM_ADDRS))
            emit(lines, f"STORE R{addr_reg}, R{data_reg}")

        elif op == "push":
            if stack_depth < max_stack_depth:
                r = rand_reg()
                emit(lines, f"PUSH R{r}")
                stack_depth += 1

        elif op == "pop":
            if stack_depth > 0:
                d = rand_reg()
                emit(lines, f"POP R{d}")
                touch(d)
                stack_depth -= 1

        elif op == "mac":
            a, b = rand_reg(), rand_reg()
            emit(lines, f"MAC R{a}, R{b}")

        elif op == "macclr":
            emit(lines, "MACCLR")

        elif op == "macread":
            d = rand_reg()
            emit(lines, f"MACREAD R{d}")
            touch(d)

        elif op == "mset":
            m = rng.choice(MATRIX_REGS)
            row, col = rng.randint(0, 3), rng.randint(0, 3)
            val = rng.randint(-128, 127)
            emit(lines, f"MSET M{m}, {row}, {col}, {val}")
            # A single-cell MSET doesn't make an MMUL-result matrix
            # INT8-safe: its other 15 cells still hold wide MMUL results.
            # Only the full 16-cell rewrite in the "mmul" arm clears that.
            if m not in mmul_result_regs:
                mset_matrix_regs.add(m)

        elif op == "mmul":
            src_candidates = [m for m in MATRIX_REGS if m in mset_matrix_regs and m not in mmul_result_regs]
            if len(src_candidates) < 2:
                # Not enough INT8-safe source matrices yet; seed one with
                # MSET instead of skipping the turn outright.
                m = rng.choice(MATRIX_REGS)
                for row in range(4):
                    for col in range(4):
                        emit(lines, f"MSET M{m}, {row}, {col}, {rng.randint(-128, 127)}")
                mset_matrix_regs.add(m)
                mmul_result_regs.discard(m)
                continue
            a, b = rng.sample(src_candidates, 2)
            d = rng.choice(MATRIX_REGS)
            emit(lines, f"MMUL M{d}, M{a}, M{b}")
            mmul_result_regs.add(d)
            mset_matrix_regs.discard(d)

        elif op == "relu":
            d = rand_reg()
            emit(lines, f"RELU R{d}")
            touch(d)  # a negative (known-nonzero) value becomes 0

        elif op == "out":
            r = rand_reg()
            emit(lines, f"OUT R{r}")

    # Balance any still-outstanding pushes so SP ends where a well-formed
    # program leaves it (not architecturally required, just keeps
    # generated programs closer to realistic call/stack discipline).
    while stack_depth > 0:
        emit(lines, f"POP R{rand_reg()}")
        stack_depth -= 1

    emit(lines, "HALT")

    with open(args.out, "w") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
